AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/*'
    - './Rakefile'

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Exclude:
    - 'lib/tasks/*.rake'

Style/IfUnlessModifier:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/StringLiterals:
  EnforcedStyle: single_quotes

Lint/Debugger:
  Enabled: true

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/MethodName:
  EnforcedStyle: snake_case
